
#define ERR_INVALID_COMMAND		"ERR INVALID COMMAND\n\r"

#define ERR_NO_CLIENT			"ERR NO CLIENT\n\r"
#define ERR_NO_SUCH_CLIENT		"ERR NO SUCH CLIENT\n\r"
#define ERR_NO_MESSAGE			"ERR NO MESSAGE\n\r"			//TODO: ERR_NO_MSG
#define ERR_POS_LOW				"ERR POSITION TOO LOW\n\r"
#define ERR_POS_HIGH			"ERR POSITION TOO HIGH\n\r"
#define ERR_COULDNT_SET_PRIORITY	"ERR COULDNT SET PRIORITY\n\r"
#define ERR_COULDNT_SET_LANGUAGE	"ERR COULDNT SET LANGUAGE\n\r"
#define ERR_ID_NOT_EXIST		"ERR ID DOESNT EXIST\n\r"

#define ERR_NOT_A_NUMBER    	"ERR GIVEN PARAMETER NOT A NUMBER\n\r"

#define OK_LANGUAGE_SET			"OK LANGUAGE SET\n\r"
#define OK_PRIORITY_SET			"OK PRIORITY SET\n\r"
#define OK_CUR_SET_FIRST		"OK CURSOR SET FIRST\n\r"
#define OK_CUR_SET_LAST			"OK CURSOR SET LAST\n\r"
#define OK_CUR_SET_POS			"OK CURSOR SET TO POSITION\n\r"
#define OK_CUR_MOV_FOR			"OK CURSOR MOVED FORWARD\n\r"
#define OK_CUR_MOV_BACK			"OK CURSOR MOVED BACKWARD\n\r"
#define OK_MESSAGE_QUEUED		"OK MESSAGE QUEUED\n\r"
#define OK_CLIENT_NAME_SET		"OK CLIENT NAME SET\n\r"
#define OK_RECEIVE_DATA				"OK RECEIVING DATA\n\r"
#define OK_		"\n\r"
#define OK_		"\n\r"
#define BYE_MSG				"HAPPY HACKING\n\r"
//#define OK_		"\n\r"


#define ERR_TOO_MUCH_DATA		"ERR TOO MUCH DATA\n\r"

