# Makefile configuration included by other Makefiles.
# BASEDIR must be defined, before this file is included!!!

# CVS revision: $Id: Makefile.config,v 1.3 2001-06-29 07:39:17 cerha Exp $
# Author: Tomas Cerha <cerha@brailcom.cz>

CC = gcc

# common flags, to be added to CFLAGS
FLAGS = -g -Wall -ansi -pedantic `glib-config --cflags` -I$(BASEDIR)/include
CFLAGS = $(FLAGS)

# common libraries, to be added to LIBS
LIB = `glib-config --libs`
LIBS = $(LIB)

