# Makefile configuration included by other Makefiles.
# CVS revision: $Id: Makefile.config,v 1.2 2001-04-10 10:42:05 cerha Exp $
# Author: Tomas Cerha <cerha@brailcom.cz>

CC = gcc
INCLUDE = ../../include
CFLAGS = -g -Wall -ansi
