# Edge TTS generic output module for Speech Dispatcher.
# It uses the edge-tts command-line client to synthesize speech
# and the generic module to play the resulting audio.

# Debug turns debugging on or off
# See speechd.conf for information where debugging information is stored
Debug 0

GenericDefaultCharset "utf-8"

GenericExecuteSynth \
"printf %s \'$DATA\' >$TMPDIR/edge-tts.txt && edge-tts -f $TMPDIR/edge-tts.txt -v \'$VOICE\' --write-media $TMPDIR/edge-tts.mp3 && $PLAY_COMMAND $TMPDIR/edge-tts.mp3"

GenericCmdDependency "edge-tts"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"

GenericLanguage "en-US" "en-US" "utf-8"
GenericLanguage "hi-IN" "hi-IN" "utf-8"
GenericLanguage "bn-IN" "bn-IN" "utf-8"
GenericLanguage "gu-IN" "gu-IN" "utf-8"

AddVoice "en-US" "MALE1" "en-US-AndrewNeural"
AddVoice "en-US" "MALE2" "en-US-BrianNeural"
AddVoice "en-US" "FEMALE1" "en-US-EmmaNeural"
AddVoice "en-US" "FEMALE2" "en-US-AriaNeural"

AddVoice "hi-IN" "MALE1" "hi-IN-MadhurNeural"
AddVoice "hi-IN" "FEMALE1" "hi-IN-SwaraNeural"

AddVoice "bn-IN" "MALE1" "bn-IN-PrabhatNeural"
AddVoice "bn-IN" "FEMALE1" "bn-IN-TanishaaNeural"

AddVoice "gu-IN" "MALE1" "gu-IN-NiranjanNeural"
AddVoice "gu-IN" "FEMALE1" "gu-IN-DhwaniNeural"

DefaultVoice "en-US-EmmaNeural"

# Copyright (C) 2026 Jyatin Singh
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
