Debug 1

GenericDefaultCharset "utf-8"

GenericLanguage "en-US" "en-US" "utf-8"
GenericLanguage "hi-IN" "hi-IN" "utf-8"
GenericLanguage "bn-IN" "bn-IN" "utf-8"
GenericLanguage "gu-IN" "gu-IN" "utf-8"

AddVoice "en-US" "MALE1" "en-US-AndrewNeural"
AddVoice "en-US" "MALE2" "en-US-BrianNeural"
AddVoice "en-US" "FEMALE1" "en-US-EmmaNeural"
AddVoice "en-US" "FEMALE2" "en-US-AriaNeural"

AddVoice "hi-IN" "MALE1" "hi-IN-MadhurNeural"
AddVoice "hi-IN" "FEMALE1" "hi-IN-SwaraNeural"

AddVoice "bn-IN" "MALE1" "bn-IN-PrabhatNeural"
AddVoice "bn-IN" "FEMALE1" "bn-IN-TanishaaNeural"

AddVoice "gu-IN" "MALE1" "gu-IN-NiranjanNeural"
AddVoice "gu-IN" "FEMALE1" "gu-IN-DhwaniNeural"

DefaultVoice "en-US-EmmaNeural"

GenericExecuteSynth "/root/bin/speechd-edge-wrapper \"$DATA\" >/dev/null 2>&1"
