\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename spd-say.info
@settitle Say client to Speech Dispatcher
@finalout
@c @setchapternewpage odd
@c %**end of header

@dircategory Sound

@direntry
* Say for Speech Dispatcher: (spd-say).       Say.
@end direntry

@titlepage
@title Say
@author Hynek Hanke <@email{hanke@@freebsoft.org}>

@page
@vskip 0pt plus 1filll

This manual documents Speech Dispatcher, version @value{VERSION}.

Copyright @copyright{} 2001, 2002, 2003 Brailcom, o.p.s.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.2
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
A copy of the license is included in the section entitled "GNU
Free Documentation License".
@end quotation

@end titlepage

@ifnottex
@node Top,  , (dir), (dir)

This manual documents Say for Speech Dispatcher, version 0.1.

Copyright @copyright{} 2001, 2002, 2003 Brailcom, o.p.s.

@quotation
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.2 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts.  A copy of the license is included
in the section entitled "GNU Free Documentation License".
@end quotation
@end ifnottex

@ifhtml
@heading Say for Speech Dispatcher
@end ifhtml

@code{spd-say} is a very simple client to Speech Dispatcher that takes some text from the
command line and even some simple parameters and passes these to Speech Dispatcher
for synthesis. The resulting syntesized speech is then played on your speakers.
It can be also used for stopping and canceling the speech on Speech dispatcher.

Usage: @code{spd-say [options] "some text"}


@table @code
@item -r or --rate
Set the rate of the speech (between -100 and +100, 0 is default).
@item -p or --pitch
Set the pitch of the speech (between -100 and +100, 0 is default).
@item -i or --volume
Set the volume (intensity) of the speech (between -100 and +100, 0 is default).
@item -o or --output-module
Set the output module.
@item -l or --language
Set the language. The parameter is an iso language code, like @code{en} or @code{cs}.
@item -t or --voice-type
Set the prefered voice type (male1, male2, male3, female1, female2,
female3, child_male, child_female).
@item -m or --punctuation-mode
Set the punctuation mode (none, some, all).
@item -s or --spelling
Spell the message
@item -w or --wait
Wait till the end of speaking the message. In this mode, spd-say returns only after
the message is fully spoken in the speakers or after it gets discarded.
@item -S or --stop
Stop the previous message in Speech Dispatcher (regardles of the client who send
it and it's priority) before saying the specified message. If no message is specified,
it just performs the stop function.
@item -C or --cancel
Similar to @code{-S}, but it stops (cancels) all the messages in all the queues in
Speech Dispatcher. Use this for total stop of speech.
@item -v or --version
Print version and copyright info.
@item -h or --help
Print a short help.
@end table

@bye

@c speechd.texi ends here

